// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpcqmwcyxleshekjtxdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwY3Ftd2N5eGxlc2hla2p0eGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMTI1NDIsImV4cCI6MjA4NTU4ODU0Mn0.E_yPvHfVjWgScG6fCCSQeBG46WkgsshHviPYI_fLxi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});